name: Deploy to Cloud Run

on:
  push:
    branches: [ main, master ]

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Cloud SDK
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up gcloud'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Enable services
      run: |
        gcloud services enable run.googleapis.com artifactregistry.googleapis.com cloudbuild.googleapis.com

    - name: Build and push image (Cloud Build)
      run: |
        gcloud builds submit --tag "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy "${{ env.SERVICE_NAME }}"           --image "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"           --region "${{ env.REGION }}"           --allow-unauthenticated           --platform managed           --port 8080           --set-env-vars MODEL_DIR=artifacts
